# coding: utf-8

"""
    Aspose.Words for Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 18.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import wordspythonsdk
from wordspythonsdk.apis.words_api import WordsApi  # noqa: E501
from wordspythonsdk.rest import ApiException


class TestWordsApi(unittest.TestCase):
    """WordsApi unit test stubs"""

    def setUp(self):
        self.api = wordspythonsdk.apis.words_api.WordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_all_revisions(self):
        """Test case for accept_all_revisions

        Accept all revisions in document  # noqa: E501
        """
        pass

    def test_classify(self):
        """Test case for classify

        Classify raw text.  # noqa: E501
        """
        pass

    def test_classify_document(self):
        """Test case for classify_document

        Classify document.  # noqa: E501
        """
        pass

    def test_create_or_update_document_property(self):
        """Test case for create_or_update_document_property

        Add new or update existing document property.  # noqa: E501
        """
        pass

    def test_delete_border(self):
        """Test case for delete_border

        Resets border properties to default values.               # noqa: E501
        """
        pass

    def test_delete_borders(self):
        """Test case for delete_borders

        Resets borders properties to default values.               # noqa: E501
        """
        pass

    def test_delete_comment(self):
        """Test case for delete_comment

        Remove comment from document.  # noqa: E501
        """
        pass

    def test_delete_document_macros(self):
        """Test case for delete_document_macros

        Remove macros from document.  # noqa: E501
        """
        pass

    def test_delete_document_property(self):
        """Test case for delete_document_property

        Delete document property.  # noqa: E501
        """
        pass

    def test_delete_document_watermark(self):
        """Test case for delete_document_watermark

        Delete watermark (for deleting last watermark from the document).  # noqa: E501
        """
        pass

    def test_delete_drawing_object(self):
        """Test case for delete_drawing_object

        Removes drawing object from document.  # noqa: E501
        """
        pass

    def test_delete_field(self):
        """Test case for delete_field

        Delete field from document.  # noqa: E501
        """
        pass

    def test_delete_fields(self):
        """Test case for delete_fields

        Remove fields from section paragraph.  # noqa: E501
        """
        pass

    def test_delete_footnote(self):
        """Test case for delete_footnote

        Removes footnote from document.  # noqa: E501
        """
        pass

    def test_delete_form_field(self):
        """Test case for delete_form_field

        Removes form field from document.  # noqa: E501
        """
        pass

    def test_delete_header_footer(self):
        """Test case for delete_header_footer

        Delete header/footer from document.  # noqa: E501
        """
        pass

    def test_delete_headers_footers(self):
        """Test case for delete_headers_footers

        Delete document headers and footers.  # noqa: E501
        """
        pass

    def test_delete_office_math_object(self):
        """Test case for delete_office_math_object

        Removes OfficeMath object from document.  # noqa: E501
        """
        pass

    def test_delete_paragraph(self):
        """Test case for delete_paragraph

        Remove paragraph from section.  # noqa: E501
        """
        pass

    def test_delete_run(self):
        """Test case for delete_run

        Removes run from document.  # noqa: E501
        """
        pass

    def test_delete_table(self):
        """Test case for delete_table

        Delete a table.  # noqa: E501
        """
        pass

    def test_delete_table_cell(self):
        """Test case for delete_table_cell

        Delete a table cell.  # noqa: E501
        """
        pass

    def test_delete_table_row(self):
        """Test case for delete_table_row

        Delete a table row.  # noqa: E501
        """
        pass

    def test_delete_unprotect_document(self):
        """Test case for delete_unprotect_document

        Unprotect document.  # noqa: E501
        """
        pass

    def test_get_border(self):
        """Test case for get_border

        Return a border.  # noqa: E501
        """
        pass

    def test_get_borders(self):
        """Test case for get_borders

        Return a collection of borders.  # noqa: E501
        """
        pass

    def test_get_comment(self):
        """Test case for get_comment

        Get comment from document.  # noqa: E501
        """
        pass

    def test_get_comments(self):
        """Test case for get_comments

        Get comments from document.  # noqa: E501
        """
        pass

    def test_get_document(self):
        """Test case for get_document

        Read document common info.  # noqa: E501
        """
        pass

    def test_get_document_bookmark_by_name(self):
        """Test case for get_document_bookmark_by_name

        Read document bookmark data by its name.  # noqa: E501
        """
        pass

    def test_get_document_bookmarks(self):
        """Test case for get_document_bookmarks

        Read document bookmarks common info.  # noqa: E501
        """
        pass

    def test_get_document_drawing_object_by_index(self):
        """Test case for get_document_drawing_object_by_index

        Read document drawing object common info by its index or convert to format specified.  # noqa: E501
        """
        pass

    def test_get_document_drawing_object_image_data(self):
        """Test case for get_document_drawing_object_image_data

        Read drawing object image data.  # noqa: E501
        """
        pass

    def test_get_document_drawing_object_ole_data(self):
        """Test case for get_document_drawing_object_ole_data

        Get drawing object OLE data.  # noqa: E501
        """
        pass

    def test_get_document_drawing_objects(self):
        """Test case for get_document_drawing_objects

        Read document drawing objects common info.  # noqa: E501
        """
        pass

    def test_get_document_field_names(self):
        """Test case for get_document_field_names

        Read document field names.  # noqa: E501
        """
        pass

    def test_get_document_hyperlink_by_index(self):
        """Test case for get_document_hyperlink_by_index

        Read document hyperlink by its index.  # noqa: E501
        """
        pass

    def test_get_document_hyperlinks(self):
        """Test case for get_document_hyperlinks

        Read document hyperlinks common info.  # noqa: E501
        """
        pass

    def test_get_document_paragraph(self):
        """Test case for get_document_paragraph

        This resource represents one of the paragraphs contained in the document.  # noqa: E501
        """
        pass

    def test_get_document_paragraph_run(self):
        """Test case for get_document_paragraph_run

        This resource represents run of text contained in the document.  # noqa: E501
        """
        pass

    def test_get_document_paragraph_run_font(self):
        """Test case for get_document_paragraph_run_font

        This resource represents font of run.  # noqa: E501
        """
        pass

    def test_get_document_paragraph_runs(self):
        """Test case for get_document_paragraph_runs

        This resource represents collection of runs in the paragraph.  # noqa: E501
        """
        pass

    def test_get_document_paragraphs(self):
        """Test case for get_document_paragraphs

        Return a list of paragraphs that are contained in the document.  # noqa: E501
        """
        pass

    def test_get_document_properties(self):
        """Test case for get_document_properties

        Read document properties info.  # noqa: E501
        """
        pass

    def test_get_document_property(self):
        """Test case for get_document_property

        Read document property info by the property name.  # noqa: E501
        """
        pass

    def test_get_document_protection(self):
        """Test case for get_document_protection

        Read document protection common info.  # noqa: E501
        """
        pass

    def test_get_document_statistics(self):
        """Test case for get_document_statistics

        Read document statistics.  # noqa: E501
        """
        pass

    def test_get_document_text_items(self):
        """Test case for get_document_text_items

        Read document text items.  # noqa: E501
        """
        pass

    def test_get_document_with_format(self):
        """Test case for get_document_with_format

        Export the document into the specified format.  # noqa: E501
        """
        pass

    def test_get_field(self):
        """Test case for get_field

        Get field from document.  # noqa: E501
        """
        pass

    def test_get_fields(self):
        """Test case for get_fields

        Get fields from document.  # noqa: E501
        """
        pass

    def test_get_footnote(self):
        """Test case for get_footnote

        Read footnote by index.  # noqa: E501
        """
        pass

    def test_get_footnotes(self):
        """Test case for get_footnotes

        Get footnotes from document.  # noqa: E501
        """
        pass

    def test_get_form_field(self):
        """Test case for get_form_field

        Returns representation of an one of the form field.  # noqa: E501
        """
        pass

    def test_get_form_fields(self):
        """Test case for get_form_fields

        Get form fields from document.  # noqa: E501
        """
        pass

    def test_get_header_footer(self):
        """Test case for get_header_footer

        Return a header/footer that is contained in the document.  # noqa: E501
        """
        pass

    def test_get_header_footer_of_section(self):
        """Test case for get_header_footer_of_section

        Return a header/footer that is contained in the document.  # noqa: E501
        """
        pass

    def test_get_header_footers(self):
        """Test case for get_header_footers

        Return a list of header/footers that are contained in the document.  # noqa: E501
        """
        pass

    def test_get_office_math_object(self):
        """Test case for get_office_math_object

        Read OfficeMath object by index.  # noqa: E501
        """
        pass

    def test_get_office_math_objects(self):
        """Test case for get_office_math_objects

        Get OfficeMath objects from document.  # noqa: E501
        """
        pass

    def test_get_section(self):
        """Test case for get_section

        Get document section by index.  # noqa: E501
        """
        pass

    def test_get_section_page_setup(self):
        """Test case for get_section_page_setup

        Get page setup of section.  # noqa: E501
        """
        pass

    def test_get_sections(self):
        """Test case for get_sections

        Return a list of sections that are contained in the document.  # noqa: E501
        """
        pass

    def test_get_table(self):
        """Test case for get_table

        Return a table.  # noqa: E501
        """
        pass

    def test_get_table_cell(self):
        """Test case for get_table_cell

        Return a table cell.  # noqa: E501
        """
        pass

    def test_get_table_cell_format(self):
        """Test case for get_table_cell_format

        Return a table cell format.  # noqa: E501
        """
        pass

    def test_get_table_properties(self):
        """Test case for get_table_properties

        Return a table properties.  # noqa: E501
        """
        pass

    def test_get_table_row(self):
        """Test case for get_table_row

        Return a table row.  # noqa: E501
        """
        pass

    def test_get_table_row_format(self):
        """Test case for get_table_row_format

        Return a table row format.  # noqa: E501
        """
        pass

    def test_get_tables(self):
        """Test case for get_tables

        Return a list of tables that are contained in the document.  # noqa: E501
        """
        pass

    def test_insert_table(self):
        """Test case for insert_table

        Adds table to document, returns added table's data.               # noqa: E501
        """
        pass

    def test_insert_table_cell(self):
        """Test case for insert_table_cell

        Adds table cell to table, returns added cell's data.               # noqa: E501
        """
        pass

    def test_insert_table_row(self):
        """Test case for insert_table_row

        Adds table row to table, returns added row's data.               # noqa: E501
        """
        pass

    def test_post_append_document(self):
        """Test case for post_append_document

        Append documents to original document.  # noqa: E501
        """
        pass

    def test_post_change_document_protection(self):
        """Test case for post_change_document_protection

        Change document protection.  # noqa: E501
        """
        pass

    def test_post_comment(self):
        """Test case for post_comment

        Updates the comment, returns updated comment's data.  # noqa: E501
        """
        pass

    def test_post_compare_document(self):
        """Test case for post_compare_document

        Compare document with original document.  # noqa: E501
        """
        pass

    def test_post_document_execute_mail_merge(self):
        """Test case for post_document_execute_mail_merge

        Execute document mail merge operation.  # noqa: E501
        """
        pass

    def test_post_document_paragraph_run_font(self):
        """Test case for post_document_paragraph_run_font

        Updates font properties, returns updated font data.  # noqa: E501
        """
        pass

    def test_post_document_save_as(self):
        """Test case for post_document_save_as

        Convert document to destination format with detailed settings and save result to storage.  # noqa: E501
        """
        pass

    def test_post_drawing_object(self):
        """Test case for post_drawing_object

        Updates drawing object, returns updated  drawing object's data.  # noqa: E501
        """
        pass

    def test_post_execute_template(self):
        """Test case for post_execute_template

        Populate document template with data.  # noqa: E501
        """
        pass

    def test_post_field(self):
        """Test case for post_field

        Updates field's properties, returns updated field's data.  # noqa: E501
        """
        pass

    def test_post_footnote(self):
        """Test case for post_footnote

        Updates footnote's properties, returns updated run's data.  # noqa: E501
        """
        pass

    def test_post_form_field(self):
        """Test case for post_form_field

        Updates properties of form field, returns updated form field.  # noqa: E501
        """
        pass

    def test_post_insert_document_watermark_image(self):
        """Test case for post_insert_document_watermark_image

        Insert document watermark image.  # noqa: E501
        """
        pass

    def test_post_insert_document_watermark_text(self):
        """Test case for post_insert_document_watermark_text

        Insert document watermark text.  # noqa: E501
        """
        pass

    def test_post_insert_page_numbers(self):
        """Test case for post_insert_page_numbers

        Insert document page numbers.  # noqa: E501
        """
        pass

    def test_post_load_web_document(self):
        """Test case for post_load_web_document

        Loads new document from web into the file with any supported format of data.  # noqa: E501
        """
        pass

    def test_post_replace_text(self):
        """Test case for post_replace_text

        Replace document text.  # noqa: E501
        """
        pass

    def test_post_run(self):
        """Test case for post_run

        Updates run's properties, returns updated run's data.  # noqa: E501
        """
        pass

    def test_post_split_document(self):
        """Test case for post_split_document

        Split document.  # noqa: E501
        """
        pass

    def test_post_update_document_bookmark(self):
        """Test case for post_update_document_bookmark

        Update document bookmark.  # noqa: E501
        """
        pass

    def test_post_update_document_fields(self):
        """Test case for post_update_document_fields

        Update (reevaluate) fields in document.  # noqa: E501
        """
        pass

    def test_put_comment(self):
        """Test case for put_comment

        Adds comment to document, returns inserted comment's data.  # noqa: E501
        """
        pass

    def test_put_convert_document(self):
        """Test case for put_convert_document

        Convert document from request content to format specified.  # noqa: E501
        """
        pass

    def test_put_create_document(self):
        """Test case for put_create_document

        Creates new document. Document is created with format which is recognized from file extensions.  Supported extentions: \".doc\", \".docx\", \".docm\", \".dot\", \".dotm\", \".dotx\", \".flatopc\", \".fopc\", \".flatopc_macro\", \".fopc_macro\", \".flatopc_template\", \".fopc_template\", \".flatopc_template_macro\", \".fopc_template_macro\", \".wordml\", \".wml\", \".rtf\"  # noqa: E501
        """
        pass

    def test_put_document_field_names(self):
        """Test case for put_document_field_names

        Read document field names.  # noqa: E501
        """
        pass

    def test_put_document_save_as_tiff(self):
        """Test case for put_document_save_as_tiff

        Convert document to tiff with detailed settings and save result to storage.  # noqa: E501
        """
        pass

    def test_put_drawing_object(self):
        """Test case for put_drawing_object

        Adds  drawing object to document, returns added  drawing object's data.  # noqa: E501
        """
        pass

    def test_put_execute_mail_merge_online(self):
        """Test case for put_execute_mail_merge_online

        Execute document mail merge online.  # noqa: E501
        """
        pass

    def test_put_execute_template_online(self):
        """Test case for put_execute_template_online

        Populate document template with data online.  # noqa: E501
        """
        pass

    def test_put_field(self):
        """Test case for put_field

        Adds field to document, returns inserted field's data.  # noqa: E501
        """
        pass

    def test_put_footnote(self):
        """Test case for put_footnote

        Adds footnote to document, returns added footnote's data.  # noqa: E501
        """
        pass

    def test_put_form_field(self):
        """Test case for put_form_field

        Adds form field to paragraph, returns added form field's data.  # noqa: E501
        """
        pass

    def test_put_header_footer(self):
        """Test case for put_header_footer

        Insert to document header or footer.  # noqa: E501
        """
        pass

    def test_put_paragraph(self):
        """Test case for put_paragraph

        Adds paragraph to document, returns added paragraph's data.  # noqa: E501
        """
        pass

    def test_put_protect_document(self):
        """Test case for put_protect_document

        Protect document.  # noqa: E501
        """
        pass

    def test_put_run(self):
        """Test case for put_run

        Adds run to document, returns added paragraph's data.  # noqa: E501
        """
        pass

    def test_reject_all_revisions(self):
        """Test case for reject_all_revisions

        Reject all revisions in document  # noqa: E501
        """
        pass

    def test_render_drawing_object(self):
        """Test case for render_drawing_object

        Renders drawing object to specified format.  # noqa: E501
        """
        pass

    def test_render_math_object(self):
        """Test case for render_math_object

        Renders math object to specified format.  # noqa: E501
        """
        pass

    def test_render_page(self):
        """Test case for render_page

        Renders page to specified format.  # noqa: E501
        """
        pass

    def test_render_paragraph(self):
        """Test case for render_paragraph

        Renders paragraph to specified format.  # noqa: E501
        """
        pass

    def test_render_table(self):
        """Test case for render_table

        Renders table to specified format.  # noqa: E501
        """
        pass

    def test_reset_cache(self):
        """Test case for reset_cache

        Resets font's cache.  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Search text in document.  # noqa: E501
        """
        pass

    def test_update_border(self):
        """Test case for update_border

        Updates border properties.               # noqa: E501
        """
        pass

    def test_update_section_page_setup(self):
        """Test case for update_section_page_setup

        Update page setup of section.  # noqa: E501
        """
        pass

    def test_update_table_cell_format(self):
        """Test case for update_table_cell_format

        Updates a table cell format.  # noqa: E501
        """
        pass

    def test_update_table_properties(self):
        """Test case for update_table_properties

        Updates a table properties.  # noqa: E501
        """
        pass

    def test_update_table_row_format(self):
        """Test case for update_table_row_format

        Updates a table row format.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
