# coding: utf-8

"""
    Aspose.Words for Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 18.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wordspythonsdk
from wordspythonsdk.rest import ApiException
from wordspythonsdk.models.bookmarks_outline_level_data import BookmarksOutlineLevelData


class TestBookmarksOutlineLevelData(unittest.TestCase):
    """ BookmarksOutlineLevelData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBookmarksOutlineLevelData(self):
        """
        Test BookmarksOutlineLevelData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = wordspythonsdk.models.bookmarks_outline_level_data.BookmarksOutlineLevelData()
        pass


if __name__ == '__main__':
    unittest.main()
