# coding: utf-8

"""
    Aspose.Words for Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 18.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wordspythonsdk
from wordspythonsdk.rest import ApiException
from wordspythonsdk.models.field_names_response import FieldNamesResponse


class TestFieldNamesResponse(unittest.TestCase):
    """ FieldNamesResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldNamesResponse(self):
        """
        Test FieldNamesResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = wordspythonsdk.models.field_names_response.FieldNamesResponse()
        pass


if __name__ == '__main__':
    unittest.main()
