# coding: utf-8

"""
    Aspose.Words for Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 18.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wordspythonsdk
from wordspythonsdk.rest import ApiException
from wordspythonsdk.models.pdf_encryption_details_data import PdfEncryptionDetailsData


class TestPdfEncryptionDetailsData(unittest.TestCase):
    """ PdfEncryptionDetailsData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPdfEncryptionDetailsData(self):
        """
        Test PdfEncryptionDetailsData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = wordspythonsdk.models.pdf_encryption_details_data.PdfEncryptionDetailsData()
        pass


if __name__ == '__main__':
    unittest.main()
