stages:
  - build&test
  - linter
  - test-publishing
  - test-publishing-test
  - publishing
  - version_tag

2.7-tests:
  stage: build&test
  before_script:
    - sudo chmod 777 -R $(find -name '*__pycache__*')  
  after_script:
    - sudo chmod 777 -R $(find -name '*__pycache__*')
  script: 
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:2.7.15 bash scripts/test-unittest.sh
  tags:
    - awcloud-linux

3.7-tests:
  stage: build&test
  before_script:
    - sudo chmod 777 -R $(find -name '*__pycache__*')  
  after_script:
    - sudo chmod 777 -R $(find -name '*__pycache__*')
  script: 
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:3.7 bash scripts/test-unittest.sh
  tags:
    - awcloud-linux

linter:
  stage: linter
  tags: 
    - awcloud-linux
  script: 
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:3.7 bash scripts/linter.sh
  artifacts:
    paths:
      - 'lintResults.txt'

merge-to-testPackage:
  stage: publishing
  before_script:
    - $env:ORIGIN += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-python.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
  script: 
    - git checkout master
    - 'git remote set-url origin $env:ORIGIN'
    - git checkout testPackage
    - git reset --hard origin/testPackage
    - git merge --no-ff --allow-unrelated-histories origin/master
    - git diff --name-status
    - git push
  only: 
    - master
  tags: 
    - awcloud
  when: manual

publish-test:
  stage: test-publishing
  script:
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:2.7.15 bash scripts/test-publish.sh $PypiLogin $PypiPass
  only:
    - testPackage
  tags:
    - awcloud-linux

test-package:
  stage: test-publishing-test
  script:
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json  
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:3.7 bash scripts/test-package.sh $WordsAppSid $WordsAppKey $WordsBaseUrl
  tags: 
    - awcloud-linux
  artifacts:
    paths:
      - nosetests.xml
    reports:
      junit:
        - nosetests.xml
  only:
    - testPackage

publish to PyPi:
  stage: publishing
  only:
    - testPackage
  before_script:
    - sudo chmod 777 -R $(find -name '*__pycache__*')
  script:
    - git reset --hard
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:2.7.15 bash scripts/publish.sh $PypiLogin $PypiPass
  tags: 
    - awcloud-linux

add version tag:
  stage: version_tag
  only:
    - testPackage
  before_script:
    - $env:ORIGIN += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-python.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
    - '$env:SDK_VERSION = ( ( ConvertFrom-Json -InputObject $jsonString ).info.version | Select-String -Pattern "^\d+\.\d+" ).Matches[0].Value'
  script: 
    - git tag -a $env:SDK_VERSION -m 'version $env:SDK_VERSION' | exit 0
    - git push $env:ORIGIN $env:SDK_VERSION    
  tags: 
    - awcloud-linux