words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('compareTestDoc1.doc', 'rb')
request_compare_data = asposewordscloud.CompareData(author='author', comparing_with_document='TestCompareDocument2.doc', date_time=dateutil.parser.isoparse('2015-10-26T00:00:00.0000000Z'))
request_comparing_document = open('compareTestDoc2.doc', 'rb')
compare_request = asposewordscloud.models.requests.CompareDocumentOnlineRequest(document=request_document, compare_data=request_compare_data, comparing_document=request_comparing_document, dest_file_name='/TestCompareDocumentOut.doc')
words_api.compare_document_online(compare_request)