words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_style_copy = asposewordscloud.StyleCopy(style_name='Heading 1')
copy_request = asposewordscloud.models.requests.CopyStyleOnlineRequest(document=request_document, style_copy=request_style_copy)
words_api.copy_style_online(copy_request)