words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_property = asposewordscloud.DocumentPropertyCreateOrUpdate(value='Imran Anwar')
create_request = asposewordscloud.models.requests.CreateOrUpdateDocumentPropertyOnlineRequest(document=request_document, property_name='AsposeAuthor', _property=request_property)
words_api.create_or_update_document_property_online(create_request)