words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_form_field = asposewordscloud.FormFieldTextInput(name='FullName', enabled=True, calculate_on_exit=True, status_text='', text_input_type='Regular', text_input_default='123', text_input_format='UPPERCASE')
insert_request = asposewordscloud.models.requests.InsertFormFieldOnlineRequest(document=request_document, form_field=request_form_field, node_path='sections/0/paragraphs/0')
words_api.insert_form_field_online(insert_request)