words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_paragraph = asposewordscloud.ParagraphInsert(text='This is a new paragraph for your document')
insert_request = asposewordscloud.models.requests.InsertParagraphOnlineRequest(document=request_document, paragraph=request_paragraph, node_path='sections/0')
words_api.insert_paragraph_online(insert_request)