words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_table = asposewordscloud.TableInsert(columns_count=5, rows_count=4)
insert_request = asposewordscloud.models.requests.InsertTableOnlineRequest(document=request_document, table=request_table)
words_api.insert_table_online(insert_request)