words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_field = asposewordscloud.FieldInsert(field_code='{ NUMPAGES }')
insert_request = asposewordscloud.models.requests.InsertFieldOnlineRequest(document=request_document, field=request_field, node_path='sections/0/paragraphs/0')
words_api.insert_field_online(insert_request)