words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_style_insert = asposewordscloud.StyleInsert(style_name='My Style', style_type='Paragraph')
insert_request = asposewordscloud.models.requests.InsertStyleOnlineRequest(document=request_document, style_insert=request_style_insert)
words_api.insert_style_online(insert_request)