words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_cell = asposewordscloud.TableCellInsert()
insert_request = asposewordscloud.models.requests.InsertTableCellOnlineRequest(document=request_document, table_row_path='sections/0/tables/2/rows/0', cell=request_cell)
words_api.insert_table_cell_online(insert_request)