words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Common/Sample.docx', 'rb')
request_page_number = asposewordscloud.PageNumber(alignment='center', format='{PAGE} of {NUMPAGES}')
insert_request = asposewordscloud.models.requests.InsertPageNumbersOnlineRequest(document=request_document, page_number=request_page_number)
words_api.insert_page_numbers_online(insert_request)