words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.doc', 'rb')
request_run = asposewordscloud.RunInsert(text='run with text')
insert_request = asposewordscloud.models.requests.InsertRunOnlineRequest(document=request_document, paragraph_path='paragraphs/1', run=request_run)
words_api.insert_run_online(insert_request)