words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.doc', 'rb')
request_list_insert = asposewordscloud.ListInsert(template='OutlineLegal')
insert_request = asposewordscloud.models.requests.InsertListOnlineRequest(document=request_document, list_insert=request_list_insert)
words_api.insert_list_online(insert_request)