words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_custom_xml_part = asposewordscloud.CustomXmlPartInsert(id='hello', data='<data>Hello world</data>')
insert_request = asposewordscloud.models.requests.InsertCustomXmlPartOnlineRequest(document=request_document, custom_xml_part=request_custom_xml_part)
words_api.insert_custom_xml_part_online(insert_request)