words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_watermark_text = asposewordscloud.WatermarkText(text='This is the text', rotation_angle=90)
insert_request = asposewordscloud.models.requests.InsertWatermarkTextOnlineRequest(document=request_document, watermark_text=request_watermark_text)
words_api.insert_watermark_text_online(insert_request)