words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_image_file = open('Common/aspose-cloud.png', 'rb')
insert_request = asposewordscloud.models.requests.InsertWatermarkImageOnlineRequest(document=request_document, image_file=request_image_file)
words_api.insert_watermark_image_online(insert_request)