words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_options = asposewordscloud.OptimizationOptions(ms_word_version='Word2002')
optimize_request = asposewordscloud.models.requests.OptimizeDocumentOnlineRequest(document=request_document, options=request_options)
words_api.optimize_document_online(optimize_request)