words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_protection_request = asposewordscloud.ProtectionRequest(new_password='123')
protect_request = asposewordscloud.models.requests.ProtectDocumentOnlineRequest(document=request_document, protection_request=request_protection_request)
words_api.protect_document_online(protect_request)