words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_replace_text = asposewordscloud.ReplaceTextParameters(old_value='aspose', new_value='aspose new')
replace_request = asposewordscloud.models.requests.ReplaceTextOnlineRequest(document=request_document, replace_text=request_replace_text)
words_api.replace_text_online(replace_request)