words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Common/test_multi_pages.docx', 'rb')
request_save_options_data = asposewordscloud.SaveOptionsData(save_format='pdf', file_name='/TestSaveAs.pdf')
save_request = asposewordscloud.models.requests.SaveAsOnlineRequest(document=request_document, save_options_data=request_save_options_data)
words_api.save_as_online(save_request)