words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_protection_request = asposewordscloud.ProtectionRequest(password='aspose')
unprotect_request = asposewordscloud.models.requests.UnprotectDocumentOnlineRequest(document=request_document, protection_request=request_protection_request)
words_api.unprotect_document_online(unprotect_request)