words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.doc', 'rb')
request_list_update = asposewordscloud.ListLevelUpdate(alignment='Right')
update_request = asposewordscloud.models.requests.UpdateListLevelOnlineRequest(document=request_document, list_id=1, list_update=request_list_update, list_level=1)
words_api.update_list_level_online(update_request)