words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_page_setup = asposewordscloud.PageSetup(rtl_gutter=True, left_margin=10, orientation='Landscape', paper_size='A5')
update_request = asposewordscloud.models.requests.UpdateSectionPageSetupOnlineRequest(document=request_document, section_index=0, page_setup=request_page_setup)
words_api.update_section_page_setup_online(update_request)