words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.doc', 'rb')
request_list_format_dto = asposewordscloud.ListFormatUpdate(list_id=2)
update_request = asposewordscloud.models.requests.UpdateParagraphListFormatOnlineRequest(document=request_document, list_format_dto=request_list_format_dto, index=0)
words_api.update_paragraph_list_format_online(update_request)