words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_drawing_object = asposewordscloud.DrawingObjectUpdate(left=0)
request_image_file = open('Common/aspose-cloud.png', 'rb')
update_request = asposewordscloud.models.requests.UpdateDrawingObjectRequest(name='Sample.docx', drawing_object=request_drawing_object, image_file=request_image_file, index=0)
words_api.update_drawing_object(update_request)