words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.doc', 'rb')
request_run = asposewordscloud.RunUpdate(text='run with text')
update_request = asposewordscloud.models.requests.UpdateRunOnlineRequest(document=request_document, paragraph_path='paragraphs/1', run=request_run, index=0)
words_api.update_run_online(update_request)