words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_field = asposewordscloud.FieldUpdate(field_code='{ NUMPAGES }')
update_request = asposewordscloud.models.requests.UpdateFieldOnlineRequest(document=request_document, field=request_field, index=0, node_path='sections/0/paragraphs/0')
words_api.update_field_online(update_request)