words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_drawing_object = asposewordscloud.DrawingObjectUpdate(left=0)
request_image_file = open('Common/aspose-cloud.png', 'rb')
update_request = asposewordscloud.models.requests.UpdateDrawingObjectOnlineRequest(document=request_document, drawing_object=request_drawing_object, image_file=request_image_file, index=0)
words_api.update_drawing_object_online(update_request)