words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_format = asposewordscloud.TableCellFormat(bottom_padding=5, fit_text=True, horizontal_merge='First', wrap_text=True)
update_request = asposewordscloud.models.requests.UpdateTableCellFormatOnlineRequest(document=request_document, table_row_path='sections/0/tables/2/rows/0', format=request_format, index=0)
words_api.update_table_cell_format_online(update_request)