words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_style_update = asposewordscloud.StyleUpdate(name='My Style')
update_request = asposewordscloud.models.requests.UpdateStyleOnlineRequest(document=request_document, style_name='Heading 1', style_update=request_style_update)
words_api.update_style_online(update_request)