words_api = WordsApi(client_id = '####-####-####-####-####', client_secret = '##################') 
request_document = open('Sample.docx', 'rb')
request_font_dto = asposewordscloud.Font(bold=True)
update_request = asposewordscloud.models.requests.UpdateRunFontOnlineRequest(document=request_document, paragraph_path='paragraphs/0', font_dto=request_font_dto, index=0)
words_api.update_run_font_online(update_request)